### ISSUE TITLE
Footloose ignite backend

### ISSUE THREAD

**Issue by kke** [save-abandoned-projects/ignite#14]
We have made a [fork of footloose](https://github.com/k0sproject/bootloose) because it's used a lot in many of the test suites for our other tools.

I just made a [PR](https://github.com/k0sproject/bootloose/pull/52) that removes the ignite backend support because ignite too went readonly and we don't really need it for anything ourself. Would you be interested in a) us keeping the current state of ignite backend support or even better b) writing a proper backend abstraction, partly based on the deleted stuff in the PR?

**Comment by woodliu** [comment]
Hi @kke ,sorry to reply so late, ignite will move on later. There is just me to contribute the code, and currently, i have something to do with my own job, so i haven't commit the code these days.
But that will going on soon.
I think ignite needs to make some change after i fix the bugs, and the interface may altered too, so remove the code from footloose is a good choice.
